name: "dwec"
services:
  node-vue1:
    image: node:24
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8085:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true



#Container de node
#Executar container i npm init quasar@latest
#ficar dins la carpera i npm run dev
  ##quasar:
  ##  image: node:24
  ##  tty: true
  ##  stdin_open: true
  ##  working_dir: /app
  ##  volumes:
  ##    - ./:/app
  ##  ports:
  ##    - "9000:9000"
  ##  environment:
  ##    - CHOKIDAR_USEPOLLING=true